### ISSUE TITLE
Kioskboard writes numbers backwards when input type=number

### ISSUE THREAD

**Issue by surexxx** [furcan/KioskBoard#1]
Is it normal when I set input type=number the kiskboard with default config writes numbers backwards?
For example: I press number buttons in order 1 2 3 and it writes 3 2 1  to html input.

![image](https://user-images.githubusercontent.com/18722513/90402270-81c7d380-e09f-11ea-9263-61bc0ff7d117.png)

Is there a way to configure it to works as input type=tel?

![image](https://user-images.githubusercontent.com/18722513/90402455-c2275180-e09f-11ea-94de-62d4d681e372.png)

**Comment by furcan** [comment]
Hi @surexxx 

Firstly thank you for using the KioskBoard.

Unfortunately, Chromium not allowing the "`selectionStart`" and the "`selectionEnd`" for the input elements if the type is "`number`". This is the why of this issue happening.

So, 

I created a solution to fix this, but I will wait a little bit to release the new version (as soon as possible). Because I already planned to do some improvements for the KioskBoard. Also, this fix will be included in the next version.

Thanks.

Furkan.

**Comment by surexxx** [comment]
@furcan thanks for quick answer. I found a workaround: set "type=tel" and it works as I expected... pls update this thread if update released.

**Comment by furcan** [comment]
Hi @surexxx .

This issue has been fixed.
[Changelog](https://github.com/furcan/KioskBoard/blob/master/CHANGELOG.md).

Thanks.

**Comment by surexxx** [comment]
It is now working in version 1.3.0
