### ISSUE TITLE
Positioning of the keyboard

### ISSUE THREAD

**Issue by kristinebow** [furcan/KioskBoard#34]
Hi, great keyboard, thanks!
Just a quick question - I’d like to position the keyboard to the top of the screen for some inputs, any suggestions on how to achieve that?

**Comment by furcan** [comment]
Hi @kristinebow ,

Unfortunately, there is no such option that sets the position of the keyboard yet. I will consider this request in the next updates. 

Thanks,
Furkan.

**Comment by faileon** [comment]
Would love to see this feature as well. Running kiosk mode with real HW kiosk the keyboard at bottom is at the level of your knees, which is not very convenient.

**Comment by kristinebow** [comment]
Yeah, I would also love it, I’ve got an issue with the keyboard blocking fields

**Comment by kristinebow** [comment]
don't mean to be annoying, but the keyboard is otherwise perfect - i just really need to position it to the top for SOME inputs, it's fine for others, I could maybe do it with CSS but it's hard to implement when I have multiple inputs that use the  keyboard :( 
any ideas?

**Comment by furcan** [comment]
Hi @kristinebow ,

No worries, it's not annoying at all. Normally I am doing open-source in my personal/free time. And I am currently in a relocation process (between countries). So, I've some difficulties with creating personal time right now. I will take care of all the issues(there are some other issues also) as soon as possible. 

About this issue; the roadmap is:
- Adding a data-attribute based option for positioning/placement. e.g. `data-kioskboard-placement="top"` (It has to be input-based because; there can be multiple input elements that needed different placements for the virtual keyboard)
- The existing `autoScroll` option and functionality will be extended/refactored by this feature.
- There is another built-in script that measures the existing space between the input and the bottom of the document itself to add the exact space for the virtual keyboard if needed. So, this script also will be refactored as well.
- Extending/refactoring the documentation.

I will keep you posted when I am done.

Thank you,
Furkan.

--- 
FYI: @faileon

**Comment by akaegi** [comment]
Hi @furcan,
thank you for your time you investigate into this project!
You say 
> There is another built-in script that measures the existing space between the input and the bottom of the document itself to add the exact space for the virtual keyboard if needed. So, this script also will be refactored as well.
Extending/refactoring the documentation.

If I understand correctly, I can expect the keyboard to be placed with enough "bottom margin" in the document if the input is too near the bottom, correct? This somehow does not seem to work in my scenario. The input is "covered" by the keyboard, see below:

![input_covered_by_KioskBoard](https://user-images.githubusercontent.com/1681061/152362477-422d72a0-3f27-4c06-afa8-a862672689f2.gif)

**Comment by furcan** [comment]
Hi @akaegi,

It is exactly as you understand. There is an example at the bottom of the page(the link below) for the demonstration. 
https://furcan.github.io/KioskBoard/

But it seems you have some trouble with the same scenario. Actually, I have to see your code to say something. (But, adding some extra bottom margin to the input element might be a solution.)

Thanks in advance,
Furkan.

**Comment by akaegi** [comment]
@furcan Wow, what a quick response, thanks alot!! Now I've seen the demo, it is well hidden ;-)
I suspect I have a problem with a fixed body/root element (using ion-app from Ionic) that interfers with your padding.
Anyway, I would like to have the extra padding added at the bottom of the "inner page" and keep the toolbar at the bottom. 
Do you think such an extension would be sensible and feasible?

**Comment by furcan** [comment]
Hi all,

[v2.1.0](https://github.com/furcan/KioskBoard/blob/main/CHANGELOG.md) has been released. 

Input based `data-kioskboard-placement` data attribute option has been added. This option sets the placement of the keyboard on `top` or `bottom` for each input/textarea element. The default value is `bottom`.

  ```html
<input class="js-kioskboard" data-kioskboard-type="keyboard" data-kioskboard-placement="top" placeholder="Your Name" />
  ```

Demo:
https://furcan.github.io/KioskBoard/

Thank you,
Furkan.
