### ISSUE TITLE
Working with react?

### ISSUE THREAD

**Issue by robergwillian** [furcan/KioskBoard#37]
Hello

I'm wondering if you could help me, how can I get this keyboard to work with react, I've added the classname and data type to the input field,

did the import KioskBoard from 'kioskboard'

and did also the Kioskboard.init and .run, however we cannot get the keyboard to render on the page. Could you shed some light?

**Comment by furcan** [comment]
Hi @robergwillian ,

I did not think about modern frameworks like React when I've created this library.

This approach might be helpful.
```jsx
const refInput = useRef(null);

// ...

useEffect(() => {
  if (inputRef.current) {
    KioskBoard.run(inputRef.current, {
      // ...init options
   });
  }
}, [inputRef]);

// ...

<input
  ref={refInput}
  type="text"
  data-kioskboard-type="all"
/>
```

I did not test the approach above 😊 
So, please test it and share your experience with me.

Many thanks,
Furkan.

**Comment by robergwillian** [comment]
Hey Furkan, 

Thank you for the quick reply, I actually got it working somewhat like you said, putting it inside a useEffect hook.

I'm implementing this virtual keyboard on a app that uses material ui components and its giving me a hard time, but it has to do with the mui stuff, when using a regular input or textarea it works like a charm.

Another question I had was about the css, I've tryed changing the css inside the node module kioskboard folder and also tryed overwriting the rules on a global css file but that didn't work, could you shed some light on this also?

btw your keyboard is awesome.

thanks again

**Comment by furcan** [comment]
Hi @robergwillian ,

Happy to hear that worked.

We should not change anything in `node_modules` for any kind of dependency. The changes always will be temporary and will be discarded when we try to add or remove this dependency later. And also, it will be changed only for our local system as well. In addition, if we are doing this just for a test scenario, we have to delete our `build` folder and rebuild our application to see the changes. (all the packages that we are using in our app already have been cached in our `build` folder instead of `node_modules` when we build/start our app.)

So, for the question about CSS, I think you can copy the style file from `node_modules` to your styles folder and you can change it and then import it.

The default path of KioskBoard has been linked to the `all-in-one`(internal CSS) file from the `dist` folder. So, you can import the KioskBoard separately from the `src` folder, instead of the `dist` one.

```jsx
// only JS (node_modules path)
import KioskBoard from 'kioskboard/src/kioskboard';

// CSS (node_modules path)
// you can copy this file to your styles folder and change it as you wanted and then, import again from your styles folder
import 'kioskboard/src/kioskboard.css'; 

```
I hope these will be helpful.


Additionally,
I am wishing you a healthy and happy new year 😊 

Thanks,
Furkan.

**Comment by kazem3d** [comment]
a very good example 
https://dev.to/0xkoji/use-kioskboard-with-reactjs-3d5o

**Comment by faizkhan12** [comment]
how do i extract the value that I have written from virtual keyboard?

**Comment by pezzeonline** [comment]
Still not working in react. The input receive the text but don't update the input box.
