### ISSUE TITLE
Vertical alignment of keyboard

### ISSUE THREAD

**Issue by surexxx** [furcan/KioskBoard#6]
I think it's a feature request, but could be usefull to others who uses the KioskBoard...
We'are started to use our displays vertically and noticed the HTML keyboard is at the bottom of the screen and not so UX ready. 
![image](https://user-images.githubusercontent.com/18722513/91157872-32e4f400-e6c6-11ea-8156-08164daadf60.png)

The expected operation would be to show keyboard under the textbox like in this picture
![image](https://user-images.githubusercontent.com/18722513/91158306-b9013a80-e6c6-11ea-8597-93db3d90bdf6.png)

@furcan what do you think how could we handle this issue easily?

**Comment by furcan** [comment]
Hi @surexxx 

I tried to create a solution for positioning the keyboard element dynamically by a variable or a parent element selector etc. but unfortunately, all ways have been created static/custom solutions and I don't wanna do that. 

I suggest using custom CSS to solve the position expectation. (Also, I wanna remind you to close the CSS animations to prevent possible positioning issues if you want to use custom CSS for positioning the keyboard element.)

e.g.

```css
div#KioskBoard-VirtualKeyboard {
    bottom: 1923px;
}
```

**Comment by surexxx** [comment]
I did the same workaround playing with position, but hope you'll find a better solution :) What is the problem with dynamic parent selector? You cannot calculate a relative position from parent as a generic and not static solution?

**Comment by furcan** [comment]
Hi @surexxx 

It is all about the CSS Animations. I will create another solution about that.

FYI. 

Thanks.

**Comment by liamcharmer** [comment]
If it helps anyone. I have a javascript listener just before I run the keyboard. 

```
      var nameEntry = document.getElementById("inputField");
      var inputRect = nameEntry.getBoundingClientRect();

      keyboardPosition.value = inputRect.bottom;
      keyboardWidth.value = inputRect.width;
      KioskBoard.run(".js-virtual-keyboard");
```

Then in my project I'm using Nuxt (vue). So I have this;

```
 <component is="style">
    #KioskBoard-VirtualKeyboard { top: {{ keyboardPosition }}px !important;
    bottom: auto !important; max-width: {{ keyboardWidth }}px !important;
    margin-top: 1vh !important; }
  </component>
  ```
  
 So that the inline style sheet will override the keyboard. In my case it makes it so the keyboard appears underneath the input field. 
  
  (I have put extra logic to then detect if the keyboard would end up being off screen, and if so then it would go above). 
  
Fortunately for my use case, there isn't any scrolling involved the page as its a fixed screen size. However it would be mega nice if this library allowed us to insert an element, and then the library would create a wrapper element, position relative it and then absolutely position the keyboard either top: 100%; or bottom: 100%; so that it would fit into the screen a bit better.
